/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'menu' : IDL.Vec(MenuItem),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Nat], [IDL.Nat], []),
  'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getRestaurantDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Restaurant)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'menu' : IDL.Vec(MenuItem),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getRestaurantDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };